return new Promise((resolve, reject) =>{
  //function
})
.then(res => {
  console.log(res)
})
.catch(err => {
  console.log(err)
})